# -*- coding: utf-8 -*-
"""Descuento

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykeSxiGkK7lZKdleiGHDDrYcsGGU63N_
"""

precio_producto = input("Ingrese el valor del producto la que desea agregar un descuento del 15%: ")

descuento = 15

resultado = 0
precio_producto = float(precio_producto)
resultado = precio_producto - (precio_producto * (descuento / 100))

print("El valor del producto con el descuento agregado es de: ","$",resultado)