# -*- coding: utf-8 -*-
"""valor variable

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ykeSxiGkK7lZKdleiGHDDrYcsGGU63N_
"""

valor_variable = 10
resultado = 0

resultado = ((((valor_variable + 5) -3) * 2) / 4 )

print(resultado)